<?php

declare(strict_types=1);

/**
 *------
 * BGA framework: © Gregory Isabelli <gisabelli@boardgamearena.com> & Emmanuel Colin <ecolin@boardgamearena.com>
 * PaxPamirSecondEd implementation : © Kabir K <kabirk@live.com>
 *
 * This code has been produced on the BGA studio platform for use on http://boardgamearena.com.
 * See http://en.boardgamearena.com/#!doc/Studio for more information.
 * -----
 *
 * material.inc.php
 *
 * PaxPamirSecondEd game material description
 *
 * Here, you can describe the material of your game with PHP variables.
 *
 * This file is loaded in your game logic class constructor, ie these variables
 * are available everywhere in your game logic code.
 *
 */

require_once 'modules/php/constants.inc.php';

// Needs to call clienttranslate, so it can't be a real const variable.
// This is also why the data isn't defined in the database.
// TODO move to another file?
$this->courtCardData = [
  0 => [
    'id' => 1,
    'type' => 'court',
    'name' => 'Mohan Lal',
    'region' => 'Kabul',
    'patriot' => NULL,
    'suit' => 'Intelligence',
    'rank' => 3,
    'prize' => 'Russian',
    'impact' => [
      0 => 'spy',
      1 => 'spy',
      2 => 'spy',
    ],
    'card_actions' => [
      0 => 'march',
    ],
    'special' => clienttranslate('TODO'),
    'flavor_text' => clienttranslate('TODO'),
  ],
  1 => [
    'id' => 2,
    'type' => 'court',
    'name' => 'Jan-Fishan Khan',
    'region' => 'Kabul',
    'patriot' => NULL,
    'suit' => 'Intelligence',
    'rank' => 2,
    'prize' => 'Russian',
    'impact' => [
      0 => 'army',
      1 => 'spy',
      2 => 'spy',
      3 => 'Military',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'battle',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  2 => [
    'id' => 3,
    'type' => 'court',
    'name' => 'Prince Akbar Khan',
    'region' => 'Kabul',
    'patriot' => 'Afghan',
    'suit' => 'Intelligence',
    'rank' => 2,
    'prize' => NULL,
    'impact' => [
      0 => 'army',
      1 => 'spy',
      2 => 'spy',
      3 => 'Military',
    ],
    'card_actions' => [
      0 => 'battle',
    ],
    'special' => clienttranslate('TODO'),
    'flavor_text' => clienttranslate('TODO'),
  ],
  3 => [
    'id' => 4,
    'type' => 'court',
    'name' => 'Charles Stoddart',
    'region' => 'Kabul',
    'patriot' => NULL,
    'suit' => 'Intelligence',
    'rank' => 1,
    'prize' => 'Afghan',
    'impact' => [
      0 => 'spy',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'gift',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  4 => [
    'id' => 5,
    'type' => 'court',
    'name' => 'Shah Shujah Durrani',
    'region' => 'Kabul',
    'patriot' => NULL,
    'suit' => 'Political',
    'rank' => 1,
    'prize' => 'Afghan',
    'impact' => [
      0 => 'tribe',
    ],
    'card_actions' => [
      0 => 'build',
    ],
    'special' => clienttranslate('TODO'),
    'flavor_text' => clienttranslate('TODO'),
  ],
  5 => [
    'id' => 6,
    'type' => 'court',
    'name' => 'Aminullah Khan Logari',
    'region' => 'Kabul',
    'patriot' => 'Afghan',
    'suit' => 'Political',
    'rank' => 1,
    'prize' => NULL,
    'impact' => [
      0 => 'army',
      1 => 'spy',
      2 => 'tribe',
    ],
    'card_actions' => [
      0 => 'battle',
      1 => 'build',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  6 => [
    'id' => 7,
    'type' => 'court',
    'name' => 'Dost Mohammad',
    'region' => 'Kabul',
    'patriot' => NULL,
    'suit' => 'Political',
    'rank' => 2,
    'prize' => NULL,
    'impact' => [
      0 => 'army',
      1 => 'spy',
      2 => 'tribe',
      3 => 'tribe',
    ],
    'card_actions' => [],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  7 => [
    'id' => 8,
    'type' => 'court',
    'name' => 'Kabul Bazaar',
    'region' => 'Kabul',
    'patriot' => NULL,
    'suit' => 'Economic',
    'rank' => 2,
    'prize' => NULL,
    'impact' => [
      0 => 'road',
      1 => 'road',
      2 => 'spy',
      3 => 'Political',
    ],
    'card_actions' => [
      0 => 'tax',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  8 => [
    'id' => 9,
    'type' => 'court',
    'name' => 'Afghan Handicrafts',
    'region' => 'Kabul',
    'patriot' => NULL,
    'suit' => 'Economic',
    'rank' => 1,
    'prize' => NULL,
    'impact' => [
      0 => 'road',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'tax',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  9 => [
    'id' => 10,
    'type' => 'court',
    'name' => 'Balkh Arsenic Mine',
    'region' => 'Kabul',
    'patriot' => NULL,
    'suit' => 'Economic',
    'rank' => 1,
    'prize' => 'Afghan',
    'impact' => [
      0 => 'road',
      1 => 'Military',
    ],
    'card_actions' => [
      0 => 'build',
      1 => 'betray',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  10 => [
    'id' => 11,
    'type' => 'court',
    'name' => 'Lapis Lazuli Mine',
    'region' => 'Kabul',
    'patriot' => 'Afghan',
    'suit' => 'Economic',
    'rank' => 2,
    'prize' => NULL,
    'impact' => [
      0 => 'road',
      1 => 'road',
    ],
    'card_actions' => [
      0 => 'tax',
      1 => 'gift',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  11 => [
    'id' => 12,
    'type' => 'court',
    'name' => 'City of Ghazni',
    'region' => 'Kabul',
    'patriot' => NULL,
    'suit' => 'Economic',
    'rank' => 3,
    'prize' => NULL,
    'impact' => [
      0 => 'road',
      1 => 'road',
      2 => 'road',
      3 => 'army',
    ],
    'card_actions' => [
      0 => 'gift',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  12 => [
    'id' => 13,
    'type' => 'court',
    'name' => 'Ghilzai Nomads',
    'region' => 'Kabul',
    'patriot' => NULL,
    'suit' => 'Economic',
    'rank' => 2,
    'prize' => 'Russian',
    'impact' => [
      0 => 'road',
      1 => 'road',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'tax',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  13 => [
    'id' => 14,
    'type' => 'court',
    'name' => 'Money Lenders',
    'region' => 'Kabul',
    'patriot' => NULL,
    'suit' => 'Economic',
    'rank' => 2,
    'prize' => NULL,
    'impact' => [
      0 => 'road',
      1 => 'road',
      2 => 'leverage',
    ],
    'card_actions' => [
      0 => 'gift',
      1 => 'build',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  14 => [
    'id' => 15,
    'type' => 'court',
    'name' => 'Durrani Royal Guard',
    'region' => 'Kabul',
    'patriot' => NULL,
    'suit' => 'Military',
    'rank' => 1,
    'prize' => NULL,
    'impact' => [
      0 => 'army',
    ],
    'card_actions' => [
      0 => 'betray',
    ],
    'special' => clienttranslate('TODO'),
    'flavor_text' => clienttranslate('TODO'),
  ],
  15 => [
    'id' => 16,
    'type' => 'court',
    'name' => 'Bala Hissar',
    'region' => 'Kabul',
    'patriot' => NULL,
    'suit' => 'Military',
    'rank' => 1,
    'prize' => NULL,
    'impact' => [
      0 => 'army',
    ],
    'card_actions' => [
      0 => 'tax',
      1 => 'betray',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  16 => [
    'id' => 17,
    'type' => 'court',
    'name' => 'Citadel of Ghazni',
    'region' => 'Kabul',
    'patriot' => NULL,
    'suit' => 'Military',
    'rank' => 1,
    'prize' => NULL,
    'impact' => [
      0 => 'army',
    ],
    'card_actions' => [
      0 => 'build',
    ],
    'special' => clienttranslate('TODO'),
    'flavor_text' => clienttranslate('TODO'),
  ],
  17 => [
    'id' => 18,
    'type' => 'court',
    'name' => 'Harry Flashman',
    'region' => 'Punjab',
    'patriot' => NULL,
    'suit' => 'Intelligence',
    'rank' => 1,
    'prize' => NULL,
    'impact' => [
      0 => 'spy',
    ],
    'card_actions' => [
      0 => 'gift',
      1 => 'betray',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  18 => [
    'id' => 19,
    'type' => 'court',
    'name' => 'Eldred Pottinger',
    'region' => 'Punjab',
    'patriot' => 'British',
    'suit' => 'Intelligence',
    'rank' => 2,
    'prize' => 'Russian',
    'impact' => [
      0 => 'spy',
      1 => 'spy',
      2 => 'Economic',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'betray',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  19 => [
    'id' => 20,
    'type' => 'court',
    'name' => 'Henry Rawlinson',
    'region' => 'Punjab',
    'patriot' => 'British',
    'suit' => 'Intelligence',
    'rank' => 1,
    'prize' => 'Russian',
    'impact' => [
      0 => 'spy',
      1 => 'Economic',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'gift',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  20 => [
    'id' => 21,
    'type' => 'court',
    'name' => 'Alexander Burnes',
    'region' => 'Punjab',
    'patriot' => NULL,
    'suit' => 'Intelligence',
    'rank' => 2,
    'prize' => 'Afghan',
    'impact' => [
      0 => 'spy',
      1 => 'spy',
    ],
    'card_actions' => [
      0 => 'march',
    ],
    'special' => clienttranslate('TODO'),
    'flavor_text' => clienttranslate('TODO'),
  ],
  21 => [
    'id' => 22,
    'type' => 'court',
    'name' => 'Geaorge Hayward',
    'region' => 'Punjab',
    'patriot' => 'British',
    'suit' => 'Intelligence',
    'rank' => 1,
    'prize' => 'Russian',
    'impact' => [
      0 => 'spy',
      1 => 'Political',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'gift',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  22 => [
    'id' => 23,
    'type' => 'court',
    'name' => 'Henry Pottinger',
    'region' => 'Punjab',
    'patriot' => 'British',
    'suit' => 'Intelligence',
    'rank' => 1,
    'prize' => 'Russian',
    'impact' => [
      0 => 'spy',
      1 => 'Economic',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'battle',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  23 => [
    'id' => 24,
    'type' => 'court',
    'name' => 'Ranjit Singh',
    'region' => 'Punjab',
    'patriot' => NULL,
    'suit' => 'Political',
    'rank' => 2,
    'prize' => NULL,
    'impact' => [
      0 => 'army',
      1 => 'tribe',
      2 => 'tribe',
    ],
    'card_actions' => [
      0 => 'betray',
    ],
    'special' => clienttranslate('TODO'),
    'flavor_text' => clienttranslate('TODO'),
  ],
  24 => [
    'id' => 25,
    'type' => 'court',
    'name' => 'Josiah Harlan',
    'region' => 'Punjab',
    'patriot' => 'Afghan',
    'suit' => 'Political',
    'rank' => 1,
    'prize' => 'British',
    'impact' => [
      0 => 'tribe',
    ],
    'card_actions' => [
      0 => 'tax',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  25 => [
    'id' => 26,
    'type' => 'court',
    'name' => 'Paolo Avitable',
    'region' => 'Punjab',
    'patriot' => NULL,
    'suit' => 'Political',
    'rank' => 1,
    'prize' => 'Afghan',
    'impact' => [
      0 => 'army',
      1 => 'tribe',
    ],
    'card_actions' => [
      0 => 'betray',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  26 => [
    'id' => 27,
    'type' => 'court',
    'name' => 'Maqpon Dynasty',
    'region' => 'Punjab',
    'patriot' => NULL,
    'suit' => 'Political',
    'rank' => 1,
    'prize' => NULL,
    'impact' => [
      0 => 'tribe',
      1 => 'leverage',
    ],
    'card_actions' => [
      0 => 'build',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  27 => [
    'id' => 28,
    'type' => 'court',
    'name' => 'Anarkali Bazaar',
    'region' => 'Punjab',
    'patriot' => NULL,
    'suit' => 'Economic',
    'rank' => 1,
    'prize' => 'Afghan',
    'impact' => [
      0 => 'road',
      1 => 'tribe',
    ],
    'card_actions' => [
      0 => 'tax',
      1 => 'build',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  28 => [
    'id' => 29,
    'type' => 'court',
    'name' => 'Khyber Pass',
    'region' => 'Punjab',
    'patriot' => NULL,
    'suit' => 'Economic',
    'rank' => 2,
    'prize' => NULL,
    'impact' => [
      0 => 'road',
      1 => 'road',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'tax',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  29 => [
    'id' => 30,
    'type' => 'court',
    'name' => 'Sikh Merchants in Lahore',
    'region' => 'Punjab',
    'patriot' => NULL,
    'suit' => 'Economic',
    'rank' => 1,
    'prize' => NULL,
    'impact' => [
      0 => 'road',
      1 => 'spy',
      2 => 'leverage',
    ],
    'card_actions' => [
      0 => 'tax',
      1 => 'gift',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  30 => [
    'id' => 31,
    'type' => 'court',
    'name' => 'Company Weapons',
    'region' => 'Punjab',
    'patriot' => NULL,
    'suit' => 'Military',
    'rank' => 1,
    'prize' => NULL,
    'impact' => [
      0 => 'army',
      1 => 'Intelligence',
    ],
    'card_actions' => [
      0 => 'tax',
      1 => 'betray',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  31 => [
    'id' => 32,
    'type' => 'court',
    'name' => 'Army of the Indus',
    'region' => 'Punjab',
    'patriot' => 'British',
    'suit' => 'Military',
    'rank' => 3,
    'prize' => 'Afghan',
    'impact' => [
      0 => 'army',
      1 => 'army',
      2 => 'army',
    ],
    'card_actions' => [
      0 => 'march',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  32 => [
    'id' => 33,
    'type' => 'court',
    'name' => 'Zorawar Singh Kahluria',
    'region' => 'Punjab',
    'patriot' => NULL,
    'suit' => 'Military',
    'rank' => 2,
    'prize' => NULL,
    'impact' => [
      0 => 'army',
      1 => 'army',
    ],
    'card_actions' => [
      0 => 'battle',
      1 => 'gift',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  33 => [
    'id' => 34,
    'type' => 'court',
    'name' => 'Sindhi Warriors',
    'region' => 'Punjab',
    'patriot' => NULL,
    'suit' => 'Military',
    'rank' => 1,
    'prize' => 'British',
    'impact' => [
      0 => 'army',
      1 => 'Economic',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'battle',
      2 => 'betray',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  34 => [
    'id' => 35,
    'type' => 'court',
    'name' => 'Hari Singh Nalwa',
    'region' => 'Punjab',
    'patriot' => NULL,
    'suit' => 'Military',
    'rank' => 2,
    'prize' => NULL,
    'impact' => [
      0 => 'army',
      1 => 'army',
      2 => 'Political',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'battle',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  35 => [
    'id' => 36,
    'type' => 'court',
    'name' => 'Bengal Native Infantry',
    'region' => 'Punjab',
    'patriot' => 'British',
    'suit' => 'Military',
    'rank' => 1,
    'prize' => 'Afghan',
    'impact' => [
      0 => 'army',
      1 => 'Intelligence',
    ],
    'card_actions' => [
      0 => 'battle',
      1 => 'betray',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  36 => [
    'id' => 37,
    'type' => 'court',
    'name' => 'Claude Wade',
    'region' => 'Persia',
    'patriot' => NULL,
    'suit' => 'Intelligence',
    'rank' => 2,
    'prize' => 'Russian',
    'impact' => [
      0 => 'spy',
      1 => 'spy',
    ],
    'card_actions' => [
      0 => 'march',
    ],
    'special' => clienttranslate('TODO'),
    'flavor_text' => clienttranslate('TODO'),
  ],
  37 => [
    'id' => 38,
    'type' => 'court',
    'name' => 'Akali Sikhs',
    'region' => 'Punjab',
    'patriot' => NULL,
    'suit' => 'Military',
    'rank' => 2,
    'prize' => 'British',
    'impact' => [
      0 => 'army',
      1 => 'army',
    ],
    'card_actions' => [
      0 => 'battle',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  38 => [
    'id' => 39,
    'type' => 'court',
    'name' => 'William Moorcroft',
    'region' => 'Kandahar',
    'patriot' => NULL,
    'suit' => 'Intelligence',
    'rank' => 1,
    'prize' => NULL,
    'impact' => [
      0 => 'spy',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'battle',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  39 => [
    'id' => 40,
    'type' => 'court',
    'name' => 'William Hay Macnaghten',
    'region' => 'Kandahar',
    'patriot' => 'British',
    'suit' => 'Intelligence',
    'rank' => 2,
    'prize' => 'Afghan',
    'impact' => [
      0 => 'spy',
      1 => 'spy',
      2 => 'leverage',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'tax',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  40 => [
    'id' => 41,
    'type' => 'court',
    'name' => 'Charles Masson',
    'region' => 'Kandahar',
    'patriot' => NULL,
    'suit' => 'Intelligence',
    'rank' => 2,
    'prize' => NULL,
    'impact' => [
      0 => 'spy',
      1 => 'spy',
    ],
    'card_actions' => [
      0 => 'build',
    ],
    'special' => clienttranslate('TODO'),
    'flavor_text' => clienttranslate('TODO'),
  ],
  41 => [
    'id' => 42,
    'type' => 'court',
    'name' => 'Barakzai Sadars',
    'region' => 'Kandahar',
    'patriot' => 'Afghan',
    'suit' => 'Political',
    'rank' => 1,
    'prize' => 'Afghan',
    'impact' => [
      0 => 'tribe',
      1 => 'leverage',
      2 => 'Economic',
    ],
    'card_actions' => [
      0 => 'build',
    ],
    'special' => clienttranslate('TODO'),
    'flavor_text' => clienttranslate('TODO'),
  ],
  42 => [
    'id' => 43,
    'type' => 'court',
    'name' => 'Giljee Nobles',
    'region' => 'Kandahar',
    'patriot' => NULL,
    'suit' => 'Political',
    'rank' => 1,
    'prize' => 'Afghan',
    'impact' => [
      0 => 'army',
      1 => 'tribe',
    ],
    'card_actions' => [
      0 => 'battle',
    ],
    'special' => clienttranslate('TODO'),
    'flavor_text' => clienttranslate('TODO'),
  ],
  43 => [
    'id' => 44,
    'type' => 'court',
    'name' => 'Baluchi Chiefs',
    'region' => 'Kandahar',
    'patriot' => NULL,
    'suit' => 'Political',
    'rank' => 1,
    'prize' => 'Russian',
    'impact' => [
      0 => 'army',
      1 => 'tribe',
    ],
    'card_actions' => [
      0 => 'tax',
      1 => 'build',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  44 => [
    'id' => 45,
    'type' => 'court',
    'name' => 'Haji Khan Kakar',
    'region' => 'Kandahar',
    'patriot' => NULL,
    'suit' => 'Political',
    'rank' => 1,
    'prize' => NULL,
    'impact' => [
      0 => 'army',
      1 => 'tribe',
    ],
    'card_actions' => [
      0 => 'gift',
      1 => 'betray',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  45 => [
    'id' => 46,
    'type' => 'court',
    'name' => 'Bank',
    'region' => 'Kandahar',
    'patriot' => NULL,
    'suit' => 'Economic',
    'rank' => 2,
    'prize' => NULL,
    'impact' => [
      0 => 'road',
      1 => 'road',
      2 => 'leverage',
      3 => 'Intelligence',
    ],
    'card_actions' => [
      0 => 'gift',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  46 => [
    'id' => 47,
    'type' => 'court',
    'name' => 'Bolan Pass',
    'region' => 'Kandahar',
    'patriot' => NULL,
    'suit' => 'Economic',
    'rank' => 2,
    'prize' => 'Russian',
    'impact' => [
      0 => 'road',
      1 => 'road',
      2 => 'army',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'gift',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  47 => [
    'id' => 48,
    'type' => 'court',
    'name' => 'Fruit Markets',
    'region' => 'Kandahar',
    'patriot' => NULL,
    'suit' => 'Economic',
    'rank' => 1,
    'prize' => NULL,
    'impact' => [
      0 => 'road',
      1 => 'Political',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'build',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  48 => [
    'id' => 49,
    'type' => 'court',
    'name' => 'Kandahari Markets',
    'region' => 'Kandahar',
    'patriot' => NULL,
    'suit' => 'Economic',
    'rank' => 1,
    'prize' => NULL,
    'impact' => [
      0 => 'road',
      1 => 'Political',
    ],
    'card_actions' => [
      0 => 'tax',
      1 => 'build',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  49 => [
    'id' => 50,
    'type' => 'court',
    'name' => 'British Regulars',
    'region' => 'Kandahar',
    'patriot' => 'British',
    'suit' => 'Military',
    'rank' => 2,
    'prize' => 'Russian',
    'impact' => [
      0 => 'army',
      1 => 'army',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'battle',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  50 => [
    'id' => 51,
    'type' => 'court',
    'name' => 'Sir John Keane',
    'region' => 'Kandahar',
    'patriot' => 'British',
    'suit' => 'Military',
    'rank' => 1,
    'prize' => 'Russian',
    'impact' => [
      0 => 'army',
    ],
    'card_actions' => [
      0 => 'battle',
    ],
    'special' => clienttranslate('TODO'),
    'flavor_text' => clienttranslate('TODO'),
  ],
  51 => [
    'id' => 52,
    'type' => 'court',
    'name' => 'Pashtun Mercenary',
    'region' => 'Kandahar',
    'patriot' => NULL,
    'suit' => 'Military',
    'rank' => 1,
    'prize' => NULL,
    'impact' => [
      0 => 'army',
      1 => 'Political',
    ],
    'card_actions' => [
      0 => 'battle',
      1 => 'tax',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  52 => [
    'id' => 53,
    'type' => 'court',
    'name' => 'Jezail Sharpshooters',
    'region' => 'Kandahar',
    'patriot' => NULL,
    'suit' => 'Military',
    'rank' => 2,
    'prize' => 'Russian',
    'impact' => [
      0 => 'army',
      1 => 'army',
      2 => 'spy',
    ],
    'card_actions' => [
      0 => 'betray',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  53 => [
    'id' => 54,
    'type' => 'court',
    'name' => 'Herati Bandits',
    'region' => 'Herat',
    'patriot' => NULL,
    'suit' => 'Intelligence',
    'rank' => 1,
    'prize' => NULL,
    'impact' => [
      0 => 'spy',
      1 => 'leverage',
    ],
    'card_actions' => [
      0 => 'tax',
    ],
    'special' => clienttranslate('TODO'),
    'flavor_text' => clienttranslate('TODO'),
  ],
  54 => [
    'id' => 55,
    'type' => 'court',
    'name' => 'Hazara Chiefs',
    'region' => 'Herat',
    'patriot' => NULL,
    'suit' => 'Political',
    'rank' => 1,
    'prize' => NULL,
    'impact' => [
      0 => 'army',
      1 => 'tribe',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'battle',
      2 => 'tax',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  55 => [
    'id' => 56,
    'type' => 'court',
    'name' => 'Yar Mohammad Alikozai',
    'region' => 'Herat',
    'patriot' => NULL,
    'suit' => 'Political',
    'rank' => 2,
    'prize' => 'Afghan',
    'impact' => [
      0 => 'tribe',
      1 => 'tribe',
      2 => 'Political',
    ],
    'card_actions' => [
      0 => 'betray',
    ],
    'special' => clienttranslate('TODO'),
    'flavor_text' => clienttranslate('TODO'),
  ],
  56 => [
    'id' => 57,
    'type' => 'court',
    'name' => 'Exiled Durrani Nobility',
    'region' => 'Herat',
    'patriot' => NULL,
    'suit' => 'Political',
    'rank' => 1,
    'prize' => 'British',
    'impact' => [
      0 => 'tribe',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'betray',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  57 => [
    'id' => 58,
    'type' => 'court',
    'name' => 'Ishaqzai Chiefs',
    'region' => 'Herat',
    'patriot' => 'Afghan',
    'suit' => 'Political',
    'rank' => 1,
    'prize' => NULL,
    'impact' => [
      0 => 'tribe',
      1 => 'Economic',
    ],
    'card_actions' => [
      0 => 'gift',
      1 => 'build',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  58 => [
    'id' => 59,
    'type' => 'court',
    'name' => 'Tajik Warband',
    'region' => 'Herat',
    'patriot' => NULL,
    'suit' => 'Military',
    'rank' => 2,
    'prize' => NULL,
    'impact' => [
      0 => 'army',
      1 => 'army',
    ],
    'card_actions' => [
      0 => 'battle',
      1 => 'betray',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  59 => [
    'id' => 60,
    'type' => 'court',
    'name' => 'Nomadic Warlord',
    'region' => 'Herat',
    'patriot' => NULL,
    'suit' => 'Military',
    'rank' => 1,
    'prize' => 'Russian',
    'impact' => [
      0 => 'army',
    ],
    'card_actions' => [
      0 => 'battle',
      1 => 'tax',
      2 => 'gift',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  60 => [
    'id' => 61,
    'type' => 'court',
    'name' => 'Karakal Sheep',
    'region' => 'Herat',
    'patriot' => NULL,
    'suit' => 'Economic',
    'rank' => 2,
    'prize' => NULL,
    'impact' => [
      0 => 'road',
      1 => 'road',
    ],
    'card_actions' => [
      0 => 'tax',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  61 => [
    'id' => 62,
    'type' => 'court',
    'name' => 'Qanat System',
    'region' => 'Herat',
    'patriot' => NULL,
    'suit' => 'Economic',
    'rank' => 1,
    'prize' => NULL,
    'impact' => [
      0 => 'road',
      1 => 'Political',
    ],
    'card_actions' => [
      0 => 'gift',
      1 => 'build',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  62 => [
    'id' => 63,
    'type' => 'court',
    'name' => 'Farah Road',
    'region' => 'Herat',
    'patriot' => NULL,
    'suit' => 'Economic',
    'rank' => 3,
    'prize' => NULL,
    'impact' => [
      0 => 'road',
      1 => 'road',
      2 => 'road',
    ],
    'card_actions' => [
      0 => 'march',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  63 => [
    'id' => 64,
    'type' => 'court',
    'name' => 'Opium Fields',
    'region' => 'Herat',
    'patriot' => NULL,
    'suit' => 'Economic',
    'rank' => 2,
    'prize' => NULL,
    'impact' => [
      0 => 'road',
      1 => 'road',
      2 => 'spy',
      3 => 'Military',
    ],
    'card_actions' => [
      0 => 'tax',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  64 => [
    'id' => 65,
    'type' => 'court',
    'name' => 'Minaret of Jam',
    'region' => 'Herat',
    'patriot' => NULL,
    'suit' => 'Economic',
    'rank' => 1,
    'prize' => NULL,
    'impact' => [
      0 => 'road',
      1 => 'army',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'battle',
      2 => 'tax',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  65 => [
    'id' => 66,
    'type' => 'court',
    'name' => 'Baluchi Smugglers',
    'region' => 'Herat',
    'patriot' => NULL,
    'suit' => 'Economic',
    'rank' => 2,
    'prize' => 'Afghan',
    'impact' => [
      0 => 'road',
      1 => 'road',
      2 => 'army',
    ],
    'card_actions' => [
      0 => 'battle',
    ],
    'special' => clienttranslate('TODO'),
    'flavor_text' => clienttranslate('TODO'),
  ],
  66 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'The Ark of Bukhara',
    'region' => 'Transcaspia',
    'patriot' => NULL,
    'suit' => 'Military',
    'rank' => 1,
    'prize' => NULL,
    'impact' => [
      0 => 'army',
      1 => 'Intelligence',
    ],
    'card_actions' => [
      0 => 'build',
    ],
    'special' => clienttranslate('TODO'),
    'flavor_text' => clienttranslate('TODO'),
  ],
  67 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Mohammad Shah',
    'region' => 'Persia',
    'patriot' => NULL,
    'suit' => 'Political',
    'rank' => 1,
    'prize' => NULL,
    'impact' => [
      0 => 'army',
      1 => 'tribe',
      2 => 'Intelligence',
    ],
    'card_actions' => [
      0 => 'build',
      1 => 'betray',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  68 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Aga Mehdi',
    'region' => 'Transcaspia',
    'patriot' => 'Russian',
    'suit' => 'Intelligence',
    'rank' => 1,
    'prize' => NULL,
    'impact' => [
      0 => 'spy',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'battle',
      2 => 'betray',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  69 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Alexander Griboyedov',
    'region' => 'Persia',
    'patriot' => 'Russian',
    'suit' => 'Intelligence',
    'rank' => 2,
    'prize' => 'Afghan',
    'impact' => [
      0 => 'spy',
      1 => 'spy',
    ],
    'card_actions' => [
      0 => 'march',
    ],
    'special' => clienttranslate('TODO'),
    'flavor_text' => clienttranslate('TODO'),
  ],
  70 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Shas Guard',
    'region' => 'Persia',
    'patriot' => NULL,
    'suit' => 'Military',
    'rank' => 1,
    'prize' => NULL,
    'impact' => [
      0 => 'army',
      1 => 'spy',
    ],
    'card_actions' => [
      0 => 'tax',
    ],
    'special' => clienttranslate('TODO'),
    'flavor_text' => clienttranslate('TODO'),
  ],
  71 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Fath Ali shah',
    'region' => 'Persia',
    'patriot' => NULL,
    'suit' => 'Political',
    'rank' => 2,
    'prize' => NULL,
    'impact' => [
      0 => 'tribe',
      1 => 'tribe',
      2 => 'Intelligence',
    ],
    'card_actions' => [],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  72 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Cossasc',
    'region' => 'Transcaspia',
    'patriot' => 'Russian',
    'suit' => 'Military',
    'rank' => 1,
    'prize' => 'British',
    'impact' => [
      0 => 'army',
      1 => 'spy',
    ],
    'card_actions' => [
      0 => 'battle',
    ],
    'special' => clienttranslate('TODO'),
    'flavor_text' => clienttranslate('TODO'),
  ],
  73 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Jean Fransois Allard',
    'region' => 'Persia',
    'patriot' => NULL,
    'suit' => 'Intelligence',
    'rank' => 1,
    'prize' => 'British',
    'impact' => [
      0 => 'spy',
      1 => 'Military',
    ],
    'card_actions' => [
      0 => 'battle',
      1 => 'build',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  74 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Civic Improvements',
    'region' => 'Persia',
    'patriot' => NULL,
    'suit' => 'Economic',
    'rank' => 2,
    'prize' => NULL,
    'impact' => [
      0 => 'road',
      1 => 'road',
      2 => 'leverage',
      3 => 'Intelligence',
    ],
    'card_actions' => [
      0 => 'build',
    ],
    'special' => clienttranslate('TODO'),
    'flavor_text' => clienttranslate('TODO'),
  ],
  75 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Mir Murad Beg',
    'region' => 'Transcaspia',
    'patriot' => NULL,
    'suit' => 'Political',
    'rank' => 1,
    'prize' => 'British',
    'impact' => [
      0 => 'spy',
      1 => 'tribe',
      2 => 'Military',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'battle',
      2 => 'tax',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  76 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Persian Army',
    'region' => 'Persia',
    'patriot' => NULL,
    'suit' => 'Military',
    'rank' => 2,
    'prize' => NULL,
    'impact' => [
      0 => 'army',
      1 => 'army',
      2 => 'Intelligence',
    ],
    'card_actions' => [
      0 => 'battle',
      1 => 'gift',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  77 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Arthur Conolly',
    'region' => 'Transcaspia',
    'patriot' => 'British',
    'suit' => 'Intelligence',
    'rank' => 1,
    'prize' => NULL,
    'impact' => [
      0 => 'spy',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'build',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  78 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Count Petrovsky',
    'region' => 'Transkaspia',
    'patriot' => 'Russian',
    'suit' => 'Military',
    'rank' => 2,
    'prize' => 'British',
    'impact' => [
      0 => 'army',
      1 => 'army',
    ],
    'card_actions' => [
      0 => 'battle',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  79 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Supplies from orenburg',
    'region' => 'Transcaspia',
    'patriot' => 'Russian',
    'suit' => 'Economic',
    'rank' => 1,
    'prize' => 'Afghan',
    'impact' => [
      0 => 'road',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'tax',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  80 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Slave Markets',
    'region' => 'Persia',
    'patriot' => NULL,
    'suit' => 'Economic',
    'rank' => 1,
    'prize' => 'British',
    'impact' => [
      0 => 'road',
      1 => 'spy',
      2 => 'leverage',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'tax',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  81 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Nasrullah Khan',
    'region' => 'Transcaspia',
    'patriot' => NULL,
    'suit' => 'Political',
    'rank' => 1,
    'prize' => 'British',
    'impact' => [
      0 => 'tribe',
    ],
    'card_actions' => [
      0 => 'tax',
      1 => 'betray',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  82 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Slave Markets',
    'region' => 'Transcaspia',
    'patriot' => NULL,
    'suit' => 'Economic',
    'rank' => 1,
    'prize' => 'British',
    'impact' => [
      0 => 'road',
      1 => 'spy',
      2 => 'leverage',
    ],
    'card_actions' => [
      0 => 'tax',
      1 => 'betray',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  83 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Abbas Mirza',
    'region' => 'Persia',
    'patriot' => NULL,
    'suit' => 'Political',
    'rank' => 1,
    'prize' => NULL,
    'impact' => [
      0 => 'army',
      1 => 'tribe',
    ],
    'card_actions' => [
      0 => 'battle',
      1 => 'tax',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  84 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Joseph Wolf',
    'region' => 'Persia',
    'patriot' => 'British',
    'suit' => 'Intelligence',
    'rank' => 1,
    'prize' => 'Afghan',
    'impact' => [
      0 => 'spy',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'gift',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  85 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Pandjeh Oasis',
    'region' => 'Transcaspia',
    'patriot' => NULL,
    'suit' => 'Economic',
    'rank' => 2,
    'prize' => 'British',
    'impact' => [
      0 => 'road',
      1 => 'road',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'tax',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  86 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Wheat Fields',
    'region' => 'Herat',
    'patriot' => NULL,
    'suit' => 'Economic',
    'rank' => 2,
    'prize' => NULL,
    'impact' => [
      0 => 'road',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'gift',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  87 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Europeans Cannons',
    'region' => 'Transcaspia',
    'patriot' => NULL,
    'suit' => 'Military',
    'rank' => 3,
    'prize' => 'British',
    'impact' => [
      0 => 'army',
      1 => 'army',
      2 => 'army',
    ],
    'card_actions' => [
      0 => 'gift',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  88 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Jan Prosper Witkiewicz',
    'region' => 'Transcaspia',
    'patriot' => 'Russian',
    'suit' => 'Intelligence',
    'rank' => 2,
    'prize' => NULL,
    'impact' => [
      0 => 'spy',
      1 => 'spy',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'build',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  89 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Russo-Persian Trade',
    'region' => 'Persia',
    'patriot' => 'Russian',
    'suit' => 'Economic',
    'rank' => 2,
    'prize' => 'British',
    'impact' => [
      0 => 'road',
      1 => 'road',
      2 => 'leverage',
    ],
    'card_actions' => [
      0 => 'tax',
      1 => 'build',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  90 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Imperial Surveyors',
    'region' => 'Transcaspia',
    'patriot' => 'Russian',
    'suit' => 'Intelligence',
    'rank' => 1,
    'prize' => NULL,
    'impact' => [
      0 => 'spy',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'gift',
      2 => 'build',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  91 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Russian Regulars',
    'region' => 'Persia',
    'patriot' => 'Russian',
    'suit' => 'Military',
    'rank' => 2,
    'prize' => 'Afghan',
    'impact' => [
      0 => 'army',
      1 => 'army',
      2 => 'Economic',
    ],
    'card_actions' => [
      0 => 'battle',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  92 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Bukharan Jews',
    'region' => 'Transcaspia',
    'patriot' => NULL,
    'suit' => 'Intelligence',
    'rank' => 1,
    'prize' => 'British',
    'impact' => [
      0 => 'spy',
      1 => 'leverage',
      2 => 'Economic',
    ],
    'card_actions' => [
      0 => 'gift',
      1 => 'build',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  93 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Ghaem Magham Farahni',
    'region' => 'Persia',
    'patriot' => NULL,
    'suit' => 'Intelligence',
    'rank' => 2,
    'prize' => NULL,
    'impact' => [
      0 => 'army',
      1 => 'spy',
      2 => 'spy',
    ],
    'card_actions' => [
      0 => 'tax',
    ],
    'special' => clienttranslate('TODO'),
    'flavor_text' => clienttranslate('TODO'),
  ],
  94 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Haji Mirza Aghasi',
    'region' => 'Persia',
    'patriot' => 'Afghan',
    'suit' => 'Political',
    'rank' => 1,
    'prize' => 'Russian',
    'impact' => [
      0 => 'tribe',
      1 => 'Intelligence',
    ],
    'card_actions' => [
      0 => 'battle',
      1 => 'betray',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  95 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Count Ivan Simonich',
    'region' => 'Persia',
    'patriot' => 'Russian',
    'suit' => 'Intelligence',
    'rank' => 2,
    'prize' => 'British',
    'impact' => [
      0 => 'spy',
      1 => 'spy',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'battle',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  96 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Anglo-Persian Trade',
    'region' => 'Persia',
    'patriot' => 'British',
    'suit' => 'Economic',
    'rank' => 1,
    'prize' => 'Russian',
    'impact' => [
      0 => 'road',
      1 => 'leverage',
    ],
    'card_actions' => [
      0 => 'tax',
      1 => 'build',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  97 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Allah Quli Bahadur',
    'region' => 'Transcaspia',
    'patriot' => NULL,
    'suit' => 'Political',
    'rank' => 1,
    'prize' => 'Russian',
    'impact' => [
      0 => 'army',
      1 => 'spy',
      2 => 'tribe',
    ],
    'card_actions' => [
      0 => 'betray',
    ],
    'special' => clienttranslate('TODO'),
    'flavor_text' => clienttranslate('TODO'),
  ],
  98 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Seaforth Highlanders',
    'region' => 'Punjab',
    'patriot' => 'British',
    'suit' => 'Military',
    'rank' => 1,
    'prize' => 'Afghan',
    'impact' => [
      0 => 'army',
      1 => 'Political',
    ],
    'card_actions' => [
      0 => 'march',
      1 => 'battle',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
  99 => [
    'id' => 999,
    'type' => 'court',
    'name' => 'Madali Khan',
    'region' => 'Transcaspia',
    'patriot' => NULL,
    'suit' => 'Political',
    'rank' => 2,
    'prize' => 'British',
    'impact' => [
      0 => 'tribe',
      1 => 'tribe',
    ],
    'card_actions' => [
      0 => 'battle',
      1 => 'betray',
    ],
    'special' => NULL,
    'flavor_text' => clienttranslate('TODO'),
  ],
];

// Excluding dominance checks
$this->eventCardData = [
  0 => [
    'id' => 105,
    'type' => 'event',
    'discard' => 'Change suit to Military',
    'discardFlavor' => clienttranslate('TODO'),
    'purchase' => 'New Tactics',
    'purchaseFlavor' => clienttranslate('TODO'),
  ],
  1 => [
    'id' => 106,
    'type' => 'event',
    'discard' => 'Embarrassment of Riches',
    'discardFlavor' => clienttranslate('TODO'),
    'purchase' => 'Koh-i-oor Recovered',
    'purchaseFlavor' => clienttranslate('TODO'),
  ],
  2 => [
    'id' => 107,
    'type' => 'event',
    'discard' => 'Disregard for Customs',
    'discardFlavor' => clienttranslate('TODO'),
    'purchase' => 'Courtly Manners',
    'purchaseFlavor' => clienttranslate('TODO'),
  ],
  3 => [
    'id' => 108,
    'type' => 'event',
    'discard' => 'Failure to Impress',
    'discardFlavor' => clienttranslate('TODO'),
    'purchase' => 'Rumor',
    'purchaseFlavor' => clienttranslate('TODO'),
  ],
  4 => [
    'id' => 109,
    'type' => 'event',
    'discard' => 'Riots in Punjab',
    'discardFlavor' => clienttranslate('TODO'),
    'purchase' => 'Conflict Fatigue',
    'purchaseFlavor' => clienttranslate('TODO'),
  ],
  5 => [
    'id' => 110,
    'type' => 'event',
    'discard' => 'Riots in Herat',
    'discardFlavor' => clienttranslate('TODO'),
    'purchase' => 'Nationalism',
    'purchaseFlavor' => clienttranslate('TODO'),
  ],
  6 => [
    'id' => 111,
    'type' => 'event',
    'discard' => 'No effect',
    'discardFlavor' => clienttranslate('TODO'),
    'purchase' => 'Public Withdrawal',
    'purchaseFlavor' => clienttranslate('TODO'),
  ],
  7 => [
    'id' => 112,
    'type' => 'event',
    'discard' => 'Riots in Kabul',
    'discardFlavor' => clienttranslate('TODO'),
    'purchase' => 'Nation Building',
    'purchaseFlavor' => clienttranslate('TODO'),
  ],
  8 => [
    'id' => 113,
    'type' => 'event',
    'discard' => 'Riots in Persia',
    'discardFlavor' => clienttranslate('TODO'),
    'purchase' => 'Backing of Persian Aristocracy',
    'purchaseFlavor' => clienttranslate('TODO'),
  ],
  9 => [
    'id' => 114,
    'type' => 'event',
    'discard' => 'Confidence Failure',
    'discardFlavor' => clienttranslate('TODO'),
    'purchase' => 'Other Persuasive Methods',
    'purchaseFlavor' => clienttranslate('TODO'),
  ],
  10 => [
    'id' => 115,
    'type' => 'event',
    'discard' => 'Change suit to Intelligence',
    'discardFlavor' => clienttranslate('TODO'),
    'purchase' => 'Pashtunwali Values',
    'purchaseFlavor' => clienttranslate('TODO'),
  ],
  11 => [
    'id' => 116,
    'type' => 'event',
    'discard' => 'Change suit to Political',
    'discardFlavor' => clienttranslate('TODO'),
    'purchase' => 'Rebuke',
    'purchaseFlavor' => clienttranslate('TODO'),
  ],
];

$this->dominanceCardData = [
  0 => [
    'id' => 101,
    'type' => 'event',
    'purchase' => 'Dominance Check',
    'discard' => 'Dominance Check',
  ],
  1 => [
    'id' => 102,
    'type' => 'event',
    'purchase' => 'Dominance Check',
    'discard' => 'Dominance Check',
  ],
  2 => [
    'id' => 103,
    'type' => 'event',
    'purchase' => 'Dominance Check',
    'discard' => 'Dominance Check',
  ],
  3 => [
    'id' => 104,
    'type' => 'event',
    'purchase' => 'Dominance Check',
    'discard' => 'Dominance Check',
  ],
];
